---
name: link-check
'on':
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    name: Markdown link check
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
